#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  view_date=""
  compiler_backend=""
  target_contracts=()
  out_dir=""
  work_dir=""
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'node' \
    'nodejs'
  _check_cmd \
    'npx'
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/$( \
    _get \
      "app" \
      "name")"
  echo \
    "${_dir}"
}

_qrview() {
  local \
    _string="${1}" \
    _oldpwd \
    _work_dir \
    _qrencode_opts=()
  _work_dir="$( \
    mktemp \
      -d)"
  _share="${_work_dir}/share.jpg"
  _qrencode_opts+=(
    -o 
      "${_share}"
  )
  _oldpwd="$( \
    pwd)"
  cd \
    "${_work_dir}"
  qrencode \
    "${_qrencode_opts[@]}" \
    "${_string}"
  cacaview \
    "${_share}"
  cd \
    "${_oldpwd}"
  rm \
    -rf \
    "${_work_dir}"
}


_set_overrides() {
  _set_override \
    "view" \
    "date" \
    "$(_get_date_human)"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Share a string using a QR code.

Usage:
  $(_get "app" "name")
    [options]
    <input_string>
  options:
     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                View date:   $(_get "view" "date")"
  _msg_info "             Input string:   $(_get "input" "string")"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2034
while \
  getopts \
    'cvh?' \
    arg; do
  case \
    "${arg}" in
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
target_string="${1}"
if [[ "${target_contracts[*]}" ==  "" ]]; then
  _msg_error \
    "no contracts given" \
    0
  _set_overrides
  _usage \
    1
fi
_set_overrides
_config_user_init \
  "$( \
    _get \
      "app" \
      "name")"
_show_config
app_opts=(
  "${in_string}"
)
_qrview \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
